version: "3.9"

networks: # definiu uma rede
  algafood-network:
    driver: bridge

services:
  
  algafood-mysql: # nome do container
    
    image: mysql:8.0 # nome da imagem
    environment:
      MYSQL_ROOT_PASSWORD: "283122Rodrigo@#" 
    ports:
      - "13306:3306"
    networks:
      - algafood-network

  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api #rodrigorrd/so-linux
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
    # ports:
    #   - "8081:8081"
    networks:
      - algafood-network
      
    depends_on: # faca dependa que comece primeiro o algafood-mysql
      - algafood-mysql
    # deploy: testar balanceamento de cargo com dois servicos
      # replicas: 2 

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api